export const FETCH_WEATHER_TRIGGER = 'FETCH_WEATHER_TRIGGER';

export const FETCH_WEATHER_REQUEST = 'FETCH_WEATHER_REQUEST';

export const FETCH_WEATHER_SUCCESS = 'FETCH_WEATHER_SUCCESS';

export const FETCH_WEATHER_FAILURE = 'FETCH_WEATHER_FAILURE';

export const CLEAR_ERROR_MESSAGE = 'CLEAR_ERROR_MESSAGE';
